name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint

  e2e:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        shard:
          - index: 0
            total: 2
          - index: 1
            total: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Resolve spec shard
        id: specs
        run: |
          SPECS=$(node ./scripts/spec-sharder.mjs ${{ matrix.shard.index }} ${{ matrix.shard.total }})
          echo "specs=$SPECS" >> "$GITHUB_OUTPUT"
        shell: bash
      - name: Run Cypress shard
        if: steps.specs.outputs.specs != ''
        run: npm run test:ci -- --spec "${{ steps.specs.outputs.specs }}"
        env:
          APP_BASE_URL: ${{ vars.APP_BASE_URL }}
          API_BASE_URL: ${{ vars.API_BASE_URL }}
      - name: Upload Mochawesome reports
        if: steps.specs.outputs.specs != ''
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-${{ matrix.shard.index }}
          path: reports/mochawesome
